// Generated by gencpp from file serial_port/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SERIAL_PORT_MESSAGE_ADDTWOINTS_H
#define SERIAL_PORT_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <serial_port/AddTwoIntsRequest.h>
#include <serial_port/AddTwoIntsResponse.h>


namespace serial_port
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace serial_port


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::serial_port::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::serial_port::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::serial_port::AddTwoInts > {
  static const char* value()
  {
    return "serial_port/AddTwoInts";
  }

  static const char* value(const ::serial_port::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::serial_port::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::serial_port::AddTwoInts > 
template<>
struct MD5Sum< ::serial_port::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::serial_port::AddTwoInts >::value();
  }
  static const char* value(const ::serial_port::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::serial_port::AddTwoIntsRequest> should match 
// service_traits::DataType< ::serial_port::AddTwoInts > 
template<>
struct DataType< ::serial_port::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::serial_port::AddTwoInts >::value();
  }
  static const char* value(const ::serial_port::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::serial_port::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::serial_port::AddTwoInts > 
template<>
struct MD5Sum< ::serial_port::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::serial_port::AddTwoInts >::value();
  }
  static const char* value(const ::serial_port::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::serial_port::AddTwoIntsResponse> should match 
// service_traits::DataType< ::serial_port::AddTwoInts > 
template<>
struct DataType< ::serial_port::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::serial_port::AddTwoInts >::value();
  }
  static const char* value(const ::serial_port::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERIAL_PORT_MESSAGE_ADDTWOINTS_H
