// Generated by gencpp from file serial_port/carOdom.msg
// DO NOT EDIT!


#ifndef SERIAL_PORT_MESSAGE_CARODOM_H
#define SERIAL_PORT_MESSAGE_CARODOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_port
{
template <class ContainerAllocator>
struct carOdom_
{
  typedef carOdom_<ContainerAllocator> Type;

  carOdom_()
    : x(0.0)
    , y(0.0)
    , vth(0.0)  {
    }
  carOdom_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , vth(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _vth_type;
  _vth_type vth;





  typedef boost::shared_ptr< ::serial_port::carOdom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_port::carOdom_<ContainerAllocator> const> ConstPtr;

}; // struct carOdom_

typedef ::serial_port::carOdom_<std::allocator<void> > carOdom;

typedef boost::shared_ptr< ::serial_port::carOdom > carOdomPtr;
typedef boost::shared_ptr< ::serial_port::carOdom const> carOdomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_port::carOdom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_port::carOdom_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace serial_port

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'serial_port': ['/home/hanwen/hw_ws/src/serial_port/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::serial_port::carOdom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_port::carOdom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_port::carOdom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_port::carOdom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_port::carOdom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_port::carOdom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_port::carOdom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c27a3de3b8c404eb1207e1eec3c23325";
  }

  static const char* value(const ::serial_port::carOdom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc27a3de3b8c404ebULL;
  static const uint64_t static_value2 = 0x1207e1eec3c23325ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_port::carOdom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_port/carOdom";
  }

  static const char* value(const ::serial_port::carOdom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_port::carOdom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x  \n\
float32 y  \n\
float32 vth\n\
";
  }

  static const char* value(const ::serial_port::carOdom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_port::carOdom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.vth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct carOdom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_port::carOdom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_port::carOdom_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "vth: ";
    Printer<float>::stream(s, indent + "  ", v.vth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_PORT_MESSAGE_CARODOM_H
