// Generated by gencpp from file serial_port/Num.msg
// DO NOT EDIT!


#ifndef SERIAL_PORT_MESSAGE_NUM_H
#define SERIAL_PORT_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_port
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : leftspeed(0.0)
    , rightspeed(0.0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : leftspeed(0.0)
    , rightspeed(0.0)  {
  (void)_alloc;
    }



   typedef float _leftspeed_type;
  _leftspeed_type leftspeed;

   typedef float _rightspeed_type;
  _rightspeed_type rightspeed;





  typedef boost::shared_ptr< ::serial_port::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_port::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::serial_port::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::serial_port::Num > NumPtr;
typedef boost::shared_ptr< ::serial_port::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_port::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_port::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace serial_port

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'serial_port': ['/home/hanwen/hw_ws/src/serial_port/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::serial_port::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_port::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_port::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_port::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_port::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_port::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_port::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b290d1f063538827f22923db0bccdbf";
  }

  static const char* value(const ::serial_port::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b290d1f06353882ULL;
  static const uint64_t static_value2 = 0x7f22923db0bccdbfULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_port::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_port/Num";
  }

  static const char* value(const ::serial_port::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_port::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 leftspeed  \n\
float32 rightspeed\n\
";
  }

  static const char* value(const ::serial_port::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_port::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftspeed);
      stream.next(m.rightspeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_port::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_port::Num_<ContainerAllocator>& v)
  {
    s << indent << "leftspeed: ";
    Printer<float>::stream(s, indent + "  ", v.leftspeed);
    s << indent << "rightspeed: ";
    Printer<float>::stream(s, indent + "  ", v.rightspeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_PORT_MESSAGE_NUM_H
